# deploying to an ec2 instance using dockerfile and github actions for backend repo only
name: Build and Deploy to EC2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

#    - name: Build and Push Docker Image
#      uses: docker/build-push-action@v5
#      with:
#        push: true
#        tags: ${{ secrets.DOCKERHUB_USERNAME }}/se-project:backend

# Added alternate way to build and push image, just in case the above doesn't works

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/se-project:backend .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/se-project:backend

    - name: SSH into EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/se-project:backend
          docker stop backend || true
          docker rm backend || true
          docker run -d -p 4000:4000 --name backend ${{ secrets.DOCKERHUB_USERNAME }}/se-project:backend





